version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
      
    working_directory: /go/src/github.com/timdurward/terraform-provider-slack
    steps:
      - checkout
      - run: go get
      - run: make test